version: '3'
services:
  django:
    build:
      context: .
      dockerfile: ./images/django/Dockerfile.alpine
      args:
        - WORKING_DIR=/srv/app
    env_file: ./source/.env
    container_name: django
    volumes:
      - ./source/:/srv/source
    ports:
      - 8000:8000
    depends_on:
      - postgres
  postgres:
    image: postgres:14.2
    container_name: postgres
    volumes:
      - ./posgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=database
